# permissions for end users to edit employees.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: employee-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: demo
    app.kubernetes.io/part-of: demo
    app.kubernetes.io/managed-by: kustomize
  name: employee-editor-role
rules:
- apiGroups:
  - cnr-na22.my.domain
  resources:
  - employees
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cnr-na22.my.domain
  resources:
  - employees/status
  verbs:
  - get
